# Generated by Django 4.2.6 on 2023-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='description',
            field=models.CharField(choices=[('cat1', 'category 1'), ('cat2', 'category 2'), ('cat3', 'category 3')], max_length=200, null=True),
        ),
    ]
